fix env

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,6 +36,18 @@ jobs:
         echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
         echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
         echo "EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }}" >> $GITHUB_ENV
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+    - name: Verify AWS credentials
+      run: |
+        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+          echo "AWS credentials are missing!"
+          exit 1
+        else
+          echo "AWS credentials are set correctly."
+        fi
 
     - name: Change permissions on EC2
       run: |
@@ -44,3 +56,7 @@ jobs:
     - name: Sync files to EC2
       run: |
         rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" --exclude '.git/' --exclude '.github/' . ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html/
+
+    - name: Restart Apache on EC2
+      run: |
+        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'sudo systemctl restart httpd'
